services:
  dex:
    image: dexidp/dex
    container_name: dex
    restart: always
    network_mode: host
    ports:
      - 3200:3200
    volumes:
      - ./dummy/dex-config.yaml:/etc/dex/config.docker.yaml
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:3200/dex/.well-known/openid-configuration" ]
      interval: 1s
      timeout: 10s
      retries: 5
  oauth:
    image: quay.io/oauth2-proxy/oauth2-proxy
    container_name: oauth
    restart: always
    network_mode: host
    ports:
      - 4180:4180
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=true
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://localhost:3200/dex
      - OAUTH2_PROXY_LOGIN_URL=http://localhost:3200/dex/auth
      - OAUTH2_PROXY_REDEEM_URL=http://localhost:3200/dex/token
      - OAUTH2_PROXY_OIDC_JWKS_URL=http://localhost:3200/dex/keys
      - OAUTH2_PROXY_UPSTREAMS=http://localhost:8000
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:4180/oauth2/callback
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_CLIENT_ID=app
      - OAUTH2_PROXY_CLIENT_SECRET=0000000000000000
      - OAUTH2_PROXY_COOKIE_SECRET=0000000000000000
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_EMAIL_DOMAINS=example.com
      - OAUTH2_PROXY_SCOPE=openid profile email groups
      - OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER=true
    depends_on:
      dex:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:4180/ping" ]
      interval: 10s
      timeout: 10s
      retries: 3